export const GALLERY_CATALOG = [
  {
    id: "faq",
    label: "FAQ",
    description: "Frequently asked questions",
    available: true,
    variantCount: 3,
  },
  {
    id: "navbar",
    label: "Navbar",
    description: "Top navigation and CTAs",
    available: true,
    variantCount: 3,
  },
  {
    id: "hero",
    label: "Hero",
    description: "Above-the-fold headline section",
    available: false,
    variantCount: 4,
  },
  {
    id: "logo-cloud",
    label: "Logo Cloud",
    description: "Trusted-by social proof",
    available: false,
    variantCount: 3,
  },
  {
    id: "features",
    label: "Features",
    description: "Product benefits and capabilities",
    available: false,
    variantCount: 3,
  },
  {
    id: "how-it-works",
    label: "How It Works",
    description: "Step-by-step product flow",
    available: false,
    variantCount: 3,
  },
  {
    id: "stats",
    label: "Stats",
    description: "Traction metrics and big numbers",
    available: false,
    variantCount: 3,
  },
  {
    id: "pricing",
    label: "Pricing",
    description: "Plans and pricing tables",
    available: false,
    variantCount: 3,
  },
  {
    id: "testimonials",
    label: "Testimonials",
    description: "Customer quotes and social proof",
    available: false,
    variantCount: 3,
  },
  {
    id: "cta",
    label: "CTA Banner",
    description: "Conversion-focused call to action",
    available: false,
    variantCount: 3,
  },
  {
    id: "team",
    label: "Team",
    description: "Founders and team members",
    available: false,
    variantCount: 3,
  },
  {
    id: "footer",
    label: "Footer",
    description: "Site footer with links and legal",
    available: false,
    variantCount: 3,
  },
];
